version: "3.9"
services:
  api:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: npm run dev:start
    env_file:
      - docker.env
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - api
